### PR TITLE
when user logged in with more than one account , prompt which one to use

### PR DESCRIPTION
**Pull request by vipconsult**
the current behaviour selects one of the account at random and uses it to login which in many cases is not the desired behaviour.

### CODE REVIEW

**Comment by shadowhand** [comment]
This is an undocumented hack and does the same thing as using `approval_prompt=force`. Not going to merge.

**Comment by vipconsult** [comment]
not really the same thing os the former displays another authorization prompt which is quite annoying from the users perspective.

with approval_prompt=force  - it displays the prompt every time
with authuser=-1 - displays the account selection box only when the user is logged in with more than one account. if only one account is logged than it uses that automatically.

**Comment by shadowhand** [comment]
Oh, I see. That makes sense, thanks for explaining.

**Comment by shadowhand** [comment]
I've tagged v1.0.1 after merging this. Thanks!

**Pull request merged**
