### PR TITLE
Add support php 8.0

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Review by shadowhand — APPROVED** [review]

**Comment by shadowhand** [comment]
Phony needs to be upgraded `^7.1`

**Comment by Yozhef** [comment]
@shadowhand maybe it makes sense for PHP 8.0 via ci to update this dependency? To still leave a larger range of support PHP version? In my opinion, test dependencies should in no way affect the number of versions of support

**Comment by shadowhand** [comment]
@Yozhef dropping PHP 7.2 support is fine, it is [EOL][1].

[1]: https://www.php.net/eol.php

**Comment by Yozhef** [comment]
@shadowhand okay -)

**Comment by Yozhef** [comment]
@shadowhand done =)

**Review by shadowhand — APPROVED** [review]

**Comment by Yozhef** [comment]
@shadowhand are we ready to make a new release?

**Comment by shadowhand** [comment]
Release 4.0.0 just tagged.

**Pull request merged**
