### PR TITLE
Added additional information about refresh tokens to the readme

### PR DESCRIPTION
**Pull request by tplaner**
Added how to obtain a refresh token and how to obtain a new refresh token along with code samples.

Relates to thephpleague/oauth2-client#370.

### CODE REVIEW

**Comment by shadowhand** [comment]
Please squash these 3 commits into one.

**Comment by tplaner** [comment]
Done, sorry about that.

**Comment by shadowhand** [comment]
Also please update your commit message to follow these rules: http://chris.beams.io/posts/git-commit/#seven-rules

**Comment by tplaner** [comment]
Better?

**Comment by shadowhand** [comment]
@tplaner It looks like [imperative subject](http://chris.beams.io/posts/git-commit/#imperative) is still not being used.

**Comment by tplaner** [comment]
Verb added: If applied, this commit will Provide more information about refresh tokens

**Comment by shadowhand** [comment]
@tpavlek :) awesome thank you.

**Comment by tpavlek** [comment]
Also thanks to @tplaner who was the only one who did anything here =P

**Comment by shadowhand** [comment]
@tplaner oops... autocomplete fail. :eyeglasses:

**Pull request merged**
